-- MySQL Script generated by MySQL Workbench
-- Tue Dec  5 23:18:24 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema administrador
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema administrador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `administrador` DEFAULT CHARACTER SET utf8 ;
USE `administrador` ;

-- -----------------------------------------------------
-- Table `administrador`.`contribuyentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`contribuyentes` (
  `id` VARCHAR(45) CHARACTER SET 'big5' NULL COMMENT 'Este es el CURP o el RFC',
  `razon_social` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido_paterno` VARCHAR(45) NULL,
  `apellido_materno` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `rfc` VARCHAR(45) NULL COMMENT 'En caso de que cuente con CURP y RFC',
  `estado` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `rfc_UNIQUE` ON `administrador`.`contribuyentes` (`rfc` ASC);


-- -----------------------------------------------------
-- Table `administrador`.`creditos_fiscales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`creditos_fiscales` (
  `folio` CHAR(50) NOT NULL,
  `monto` DOUBLE(15,8) NOT NULL,
  `documento_determinante` CHAR(50) NOT NULL,
  `origen_credito` CHAR(50) NOT NULL,
  `estatus` TINYINT NULL DEFAULT 1,
  `contribuyentes_id` VARCHAR(45) CHARACTER SET 'big5' NOT NULL,
  PRIMARY KEY (`folio`),
  CONSTRAINT `fk_creditos_fiscales_contribuyentes`
    FOREIGN KEY (`contribuyentes_id`)
    REFERENCES `administrador`.`contribuyentes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_creditos_fiscales_contribuyentes1_idx` ON `administrador`.`creditos_fiscales` (`contribuyentes_id` ASC);


-- -----------------------------------------------------
-- Table `administrador`.`Deudor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`Deudor` (
  `Nombre` INT NOT NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administrador`.`peritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`peritos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido_paterno` VARCHAR(45) NULL,
  `apellido_materno` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administrador`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`estados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administrador`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`municipios` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `estados_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_municipios_estados_1`
    FOREIGN KEY (`estados_id`)
    REFERENCES `administrador`.`estados` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_municipios_estados_idx` ON `administrador`.`municipios` (`estados_id` ASC);


-- -----------------------------------------------------
-- Table `administrador`.`domicilios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`domicilios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cp` INT NOT NULL,
  `int` VARCHAR(45) NULL,
  `ext` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NOT NULL,
  `colonia` CHAR(50) NOT NULL,
  `estados_id` INT NOT NULL,
  `municipios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_domicilios_estados`
    FOREIGN KEY (`estados_id`)
    REFERENCES `administrador`.`estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_domicilios_municipios`
    FOREIGN KEY (`municipios_id`)
    REFERENCES `administrador`.`municipios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_domicilios_estados_idx` ON `administrador`.`domicilios` (`estados_id` ASC);

CREATE INDEX `fk_domicilios_municipios_idx` ON `administrador`.`domicilios` (`municipios_id` ASC);


-- -----------------------------------------------------
-- Table `administrador`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administrador`.`subcategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`subcategorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administrador`.`depositarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`depositarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido_paterno` VARCHAR(45) NULL,
  `apellido_materno` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administrador`.`bienes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`bienes` (
  `numero_control` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `estado` TINYINT(1) NULL DEFAULT 1,
  `cantidad` INT(10) NULL,
  `deposito_id` INT NOT NULL,
  `depositarios_id` INT NOT NULL,
  PRIMARY KEY (`numero_control`),
  CONSTRAINT `fk_bienes_domicilios1`
    FOREIGN KEY (`deposito_id`)
    REFERENCES `administrador`.`domicilios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bienes_depositarios1`
    FOREIGN KEY (`depositarios_id`)
    REFERENCES `administrador`.`depositarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_bienes_domicilios1_idx` ON `administrador`.`bienes` (`deposito_id` ASC);

CREATE INDEX `fk_bienes_depositarios1_idx` ON `administrador`.`bienes` (`depositarios_id` ASC);


-- -----------------------------------------------------
-- Table `administrador`.`imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`imagenes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `bienes_numero_control` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_imagenes_bienes1`
    FOREIGN KEY (`bienes_numero_control`)
    REFERENCES `administrador`.`bienes` (`numero_control`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `administrador`.`imagenes` (`nombre` ASC);

CREATE INDEX `fk_imagenes_bienes1_idx` ON `administrador`.`imagenes` (`bienes_numero_control` ASC);


-- -----------------------------------------------------
-- Table `administrador`.`categorias_subcategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`categorias_subcategorias` (
  `categorias_id` INT NOT NULL,
  `subcategorias_id` INT NOT NULL,
  PRIMARY KEY (`categorias_id`, `subcategorias_id`),
  CONSTRAINT `fk_bienes_has_categorias_categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `administrador`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categorias_subcategorias_subcategorias1`
    FOREIGN KEY (`subcategorias_id`)
    REFERENCES `administrador`.`subcategorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_bienes_has_categorias_categorias1_idx` ON `administrador`.`categorias_subcategorias` (`categorias_id` ASC);

CREATE INDEX `fk_categorias_subcategorias_subcategorias1_idx` ON `administrador`.`categorias_subcategorias` (`subcategorias_id` ASC);


-- -----------------------------------------------------
-- Table `administrador`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`permisos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administrador`.`rols`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`rols` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administrador`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido_paterno` VARCHAR(45) NULL,
  `apellido_materno` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `estado` TINYINT NULL DEFAULT 1,
  `remember_token` VARCHAR(255) NULL,
  `rols_id` INT NOT NULL DEFAULT 2,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_users_rols1`
    FOREIGN KEY (`rols_id`)
    REFERENCES `administrador`.`rols` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `correo_UNIQUE` ON `administrador`.`users` (`email` ASC);

CREATE INDEX `fk_users_rols1_idx` ON `administrador`.`users` (`rols_id` ASC);


-- -----------------------------------------------------
-- Table `administrador`.`motivos_bajas_creditos_fiscales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`motivos_bajas_creditos_fiscales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administrador`.`bajas_creditos_fiscales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`bajas_creditos_fiscales` (
  `baja` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `comentarios` VARCHAR(255) NOT NULL,
  `creditos_fiscales_folio` CHAR(15) NOT NULL,
  PRIMARY KEY (`baja`, `usuarios_id`),
  CONSTRAINT `fk_creditos_fiscales_has_motivos_bajas_creditos_fiscales_moti1`
    FOREIGN KEY (`baja`)
    REFERENCES `administrador`.`motivos_bajas_creditos_fiscales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_altas_bajas_creditos_fiscales_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `administrador`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bajas_creditos_fiscales_creditos_fiscales1`
    FOREIGN KEY (`creditos_fiscales_folio`)
    REFERENCES `administrador`.`creditos_fiscales` (`folio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_creditos_fiscales_has_motivos_bajas_creditos_fiscales_mo_idx` ON `administrador`.`bajas_creditos_fiscales` (`baja` ASC);

CREATE INDEX `fk_altas_bajas_creditos_fiscales_usuarios1_idx` ON `administrador`.`bajas_creditos_fiscales` (`usuarios_id` ASC);

CREATE INDEX `fk_bajas_creditos_fiscales_creditos_fiscales1_idx` ON `administrador`.`bajas_creditos_fiscales` (`creditos_fiscales_folio` ASC);


-- -----------------------------------------------------
-- Table `administrador`.`direcciones_contribuyentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`direcciones_contribuyentes` (
  `domicilios_id` INT NOT NULL,
  `contribuyentes_id` VARCHAR(45) CHARACTER SET 'big5' NOT NULL,
  PRIMARY KEY (`domicilios_id`),
  CONSTRAINT `fk_contribuyentes_has_domicilios_domicilios`
    FOREIGN KEY (`domicilios_id`)
    REFERENCES `administrador`.`domicilios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_direcciones_contribuyentes_fisicos_contribuyentes`
    FOREIGN KEY (`contribuyentes_id`)
    REFERENCES `administrador`.`contribuyentes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_contribuyentes_has_domicilios_domicilios1_idx` ON `administrador`.`direcciones_contribuyentes` (`domicilios_id` ASC);

CREATE INDEX `fk_direcciones_contribuyentes_fisicos_contribuyentes1_idx` ON `administrador`.`direcciones_contribuyentes` (`contribuyentes_id` ASC);


-- -----------------------------------------------------
-- Table `administrador`.`permisos_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`permisos_usuarios` (
  `usuarios_id` INT NOT NULL,
  `permisos_id` INT NOT NULL,
  CONSTRAINT `fk_usuarios_has_permisos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `administrador`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_permisos_permisos1`
    FOREIGN KEY (`permisos_id`)
    REFERENCES `administrador`.`permisos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuarios_has_permisos_permisos1_idx` ON `administrador`.`permisos_usuarios` (`permisos_id` ASC);

CREATE INDEX `fk_usuarios_has_permisos_usuarios1_idx` ON `administrador`.`permisos_usuarios` (`usuarios_id` ASC);


-- -----------------------------------------------------
-- Table `administrador`.`embargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`embargos` (
  `Creditos_Fiscales_folio` CHAR(50) NOT NULL,
  `documento` VARCHAR(45) NULL,
  `fecha` VARCHAR(45) NULL,
  `bienes_numero_control` VARCHAR(45) NOT NULL,
  CONSTRAINT `fk_Creditos_Fiscales_has_bienes_Creditos_Fiscales1`
    FOREIGN KEY (`Creditos_Fiscales_folio`)
    REFERENCES `administrador`.`creditos_fiscales` (`folio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_embargos_bienes1`
    FOREIGN KEY (`bienes_numero_control`)
    REFERENCES `administrador`.`bienes` (`numero_control`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Creditos_Fiscales_has_bienes_Creditos_Fiscales1_idx` ON `administrador`.`embargos` (`Creditos_Fiscales_folio` ASC);

CREATE INDEX `fk_embargos_bienes1_idx` ON `administrador`.`embargos` (`bienes_numero_control` ASC);


-- -----------------------------------------------------
-- Table `administrador`.`bienes_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`bienes_categorias` (
  `categorias_id` INT NOT NULL,
  `subcategoria_id` INT NULL DEFAULT NULL,
  `subsubcategoria_id` INT NULL DEFAULT NULL,
  `bienes_numero_control` VARCHAR(45) NOT NULL,
  CONSTRAINT `fk_articulos_has_categorias_categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `administrador`.`categorias` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_articulos_categorias_bienes1`
    FOREIGN KEY (`bienes_numero_control`)
    REFERENCES `administrador`.`bienes` (`numero_control`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_articulos_has_categorias_categorias1_idx` ON `administrador`.`bienes_categorias` (`categorias_id` ASC);

CREATE INDEX `fk_articulos_categorias_bienes1_idx` ON `administrador`.`bienes_categorias` (`bienes_numero_control` ASC);


-- -----------------------------------------------------
-- Table `administrador`.`valuaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`valuaciones` (
  `peritos_id` INT NOT NULL,
  `monto` FLOAT NOT NULL,
  `fecha` DATE NOT NULL,
  `numero_dictamen` CHAR(255) NOT NULL,
  `bienes_numero_control` VARCHAR(45) NOT NULL,
  CONSTRAINT `fk_valuaciones_peritos`
    FOREIGN KEY (`peritos_id`)
    REFERENCES `administrador`.`peritos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_valuaciones_bienes1`
    FOREIGN KEY (`bienes_numero_control`)
    REFERENCES `administrador`.`bienes` (`numero_control`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_articulos_has_peritos_peritos1_idx` ON `administrador`.`valuaciones` (`peritos_id` ASC);

CREATE INDEX `fk_valuaciones_bienes1_idx` ON `administrador`.`valuaciones` (`bienes_numero_control` ASC);


-- -----------------------------------------------------
-- Table `administrador`.`postores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`postores` (
  `RFC` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido_paterno` VARCHAR(45) NULL,
  `apellido_materno` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `domicilios_id` INT NOT NULL,
  PRIMARY KEY (`RFC`),
  CONSTRAINT `fk_postores_domicilios1`
    FOREIGN KEY (`domicilios_id`)
    REFERENCES `administrador`.`domicilios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_postores_domicilios1_idx` ON `administrador`.`postores` (`domicilios_id` ASC);


-- -----------------------------------------------------
-- Table `administrador`.`remates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`remates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `estado` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `administrador`.`remates` (`id` ASC);


-- -----------------------------------------------------
-- Table `administrador`.`pujas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`pujas` (
  `postores_RFC` INT NOT NULL,
  `remate_id` INT NOT NULL,
  `oferta` FLOAT NOT NULL,
  CONSTRAINT `fk_pujas_postores`
    FOREIGN KEY (`postores_RFC`)
    REFERENCES `administrador`.`postores` (`RFC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pujas_remate1`
    FOREIGN KEY (`remate_id`)
    REFERENCES `administrador`.`remates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pujas_postores1_idx` ON `administrador`.`pujas` (`postores_RFC` ASC);

CREATE INDEX `fk_pujas_remate1_idx` ON `administrador`.`pujas` (`remate_id` ASC);


-- -----------------------------------------------------
-- Table `administrador`.`subsubcategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`subsubcategorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administrador`.`motivos_bajas_bienes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`motivos_bajas_bienes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administrador`.`bajas_bienes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`bajas_bienes` (
  `motivos_bajas_articulos_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `comentarios` VARCHAR(255) NULL,
  `bienes_numero_control` VARCHAR(45) NOT NULL,
  CONSTRAINT `fk_articulos_has_motivos_bajas_articulos_motivos_bajas_articu1`
    FOREIGN KEY (`motivos_bajas_articulos_id`)
    REFERENCES `administrador`.`motivos_bajas_bienes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bajas_articulos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `administrador`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bajas_bienes_bienes1`
    FOREIGN KEY (`bienes_numero_control`)
    REFERENCES `administrador`.`bienes` (`numero_control`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_articulos_has_motivos_bajas_articulos_motivos_bajas_arti_idx` ON `administrador`.`bajas_bienes` (`motivos_bajas_articulos_id` ASC);

CREATE INDEX `fk_bajas_articulos_usuarios1_idx` ON `administrador`.`bajas_bienes` (`usuarios_id` ASC);

CREATE INDEX `fk_bajas_bienes_bienes1_idx` ON `administrador`.`bajas_bienes` (`bienes_numero_control` ASC);


-- -----------------------------------------------------
-- Table `administrador`.`lotes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`lotes` (
  `remate_id` INT NOT NULL,
  `bienes_numero_control` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`remate_id`),
  CONSTRAINT `fk_remate`
    FOREIGN KEY (`remate_id`)
    REFERENCES `administrador`.`remates` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_lotes_bienes1`
    FOREIGN KEY (`bienes_numero_control`)
    REFERENCES `administrador`.`bienes` (`numero_control`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_lotes_remate1_idx` ON `administrador`.`lotes` (`remate_id` ASC);

CREATE INDEX `fk_lotes_bienes1_idx` ON `administrador`.`lotes` (`bienes_numero_control` ASC);


-- -----------------------------------------------------
-- Table `administrador`.`subcategorias_subsubcategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`subcategorias_subsubcategorias` (
  `subcategorias_id` INT NOT NULL,
  `subsubcategorias_id` INT NOT NULL,
  PRIMARY KEY (`subcategorias_id`, `subsubcategorias_id`),
  CONSTRAINT `fk_subcategorias_has_subsubcategorias_subcategorias1`
    FOREIGN KEY (`subcategorias_id`)
    REFERENCES `administrador`.`subcategorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subcategorias_has_subsubcategorias_subsubcategorias1`
    FOREIGN KEY (`subsubcategorias_id`)
    REFERENCES `administrador`.`subsubcategorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_subcategorias_has_subsubcategorias_subsubcategorias1_idx` ON `administrador`.`subcategorias_subsubcategorias` (`subsubcategorias_id` ASC);

CREATE INDEX `fk_subcategorias_has_subsubcategorias_subcategorias1_idx` ON `administrador`.`subcategorias_subsubcategorias` (`subcategorias_id` ASC);

USE `administrador` ;

-- -----------------------------------------------------
-- Placeholder table for view `administrador`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `administrador`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administrador`.`view1`;
USE `administrador`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
