@extends("layout.master")
@section("title","contribuyentes")
@section("content")
    @include("contribuyentes.tabla")
@endsection
@section("scripts")
    {{Html::script("js/variables.js")}}
    {{Html::script("js/funciones.js")}}
    {{Html::script("js/contribuyentes.js")}}
@endsection